language: go

go:
  - master

services:
  - docker

dist: trusty

matrix:
  allow_failures:
    - go: master
  fast_finish: true

env:
  - NODE_VERSION="12.13.0"

before_install:
  - nvm install $NODE_VERSION

install:
  - docker-compose -f docker-compose.override.yml up -d
  - go mod download
  - npm i -g prisma

before_script:
  - awk -f ./docker/replace.awk ./docker/to-local.txt ./prisma/prisma.yml | tee ./prisma/prisma.yml
  - prisma deploy

script:
  - go test -v ./tests/*
