language: go node_js
go:
  - master

node_js:
  - "stable"

services:
  - docker

dist: trusty

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - docker-compose -f docker-compose.override.yml up -d
  - npm i -g prisma
  - prisma deploy
  - go mod download

script:
  - go test -v ./tests/*
