language: go node_js
go:
  - master

node_js:
  - "stable"

services:
  - docker

dist: trusty

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - "docker-compose up -d"
  - npm i -g prisma
  - prisma deploy
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
  - glide install

script:
  - go test -v ./tests/*
