version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/msanvarov/gin-rest-prisma-boilerplate
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: docker-compose up -d
      - run: |
          curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - run: npm i -g prisma && cd prisma && prisma deploy
      - run: go test -v ./tests/*
